# Generated by Django 5.0.6 on 2024-06-17 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.date(1900, 1, 1), verbose_name='Дата производства продукта'),
        ),
    ]
